# Generated by Django 3.0.6 on 2020-11-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='studies',
            new_name='studies_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='studies_2',
        ),
    ]
