# Generated by Django 3.0.6 on 2020-11-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201102_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='studies_1',
            new_name='studies',
        ),
    ]
