# Generated by Django 3.0.6 on 2020-11-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201102_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='rough_xpath_description',
            field=models.CharField(default='rough description', max_length=150),
            preserve_default=False,
        ),
    ]
