# Generated by Django 3.0.4 on 2020-04-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cdafile_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cdafile',
            unique_together=set(),
        ),
    ]
