# Generated by Django 3.0.6 on 2020-11-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_condition_rough_xpath_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='negative_xpath',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
