# Generated by Django 3.0.4 on 2020-04-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cdafile_cda_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdafile',
            name='cda_id',
            field=models.FloatField(),
        ),
    ]
