# Generated by Django 3.0.6 on 2020-11-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201111_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='description',
        ),
        migrations.AddField(
            model_name='study',
            name='criterion_count',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='elga_criterion_count',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='head_of_study',
            field=models.CharField(blank=True, default='Keine Angabe', max_length=600),
        ),
        migrations.AddField(
            model_name='study',
            name='head_of_study_contact',
            field=models.CharField(blank=True, default='Keine Angaben', max_length=800),
        ),
    ]
