# Generated by Django 3.0.6 on 2020-11-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201115_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='only_current_patient_cohort',
        ),
    ]
