# Generated by Django 3.1.4 on 2020-12-01 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_patient_patient_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_result',
        ),
        migrations.CreateModel(
            name='Patient_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_result', models.JSONField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_result', to='api.patient')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_result', to='api.study')),
            ],
        ),
    ]
