# Generated by Django 3.1.4 on 2020-12-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201201_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_result',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
