# Generated by Django 3.1.4 on 2020-12-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201201_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='studies',
        ),
    ]
