# Generated by Django 3.0.4 on 2020-04-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmenttool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdafile',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='recruitmenttool.Patient'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='description',
            field=models.CharField(blank=True, default='Keine Beschreibung', max_length=600),
        ),
        migrations.AlterField(
            model_name='criterium',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteriums', to='recruitmenttool.Criteria'),
        ),
    ]
