# Generated by Django 3.0.4 on 2020-04-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmenttool', '0002_auto_20200407_0850'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criterium',
            unique_together={('criteria',)},
        ),
    ]
