# Generated by Django 3.0.4 on 2020-04-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmenttool', '0003_auto_20200407_0858'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cdafile',
            unique_together={('patient',)},
        ),
    ]
