# Generated by Django 3.0.4 on 2020-04-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmenttool', '0004_auto_20200407_1002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criterium',
            unique_together=set(),
        ),
    ]
